
type_of_lstm='rhn'

learning_rate=0.25
gradient_clip=10
batch_size=20
layer_norm=false
keep_prob=0.75
keep_prob_r=0.75
weight_decay=1e-9
optimizer='sgd'

[config]
vocab_size=10000
num_steps=35
embedding_size=642

[config_lstm]
recurrent_highway=true
recurrence_depth=4
num_units=642
