model='hsg'

# RHN with HSG (highway state gating)
# learning rate: 0.2
# decay after 20 epoch: divide by 1.02
# epoch 55

learning_rate=0.2
max_epoch=20
learning_rate_decay=1.02

gradient_clip=10
batch_size=20
keep_prob=[0.75, 0.25]  # embedding, output
keep_prob_r=[0.25, 0.75]  # input, state
weight_decay=1e-9
optimizer='sgd'
ini_scale=0.04

[config]
vocab_size=10000
num_steps=35
embedding_size=830

highway_state_gate=true
recurrent_highway=true
recurrence_depth=40
num_units=830

coupling_gate=true
forget_bias = -2.5
