## WIP
#
#
#model='hypernets'
#learning_rate=0.5
#gradient_clip=10
#batch_size=20
#layer_norm=false
#keep_prob=0.75
#keep_prob_r=0.75
#weight_decay=1e-9
#optimizer='sgd'
#
#[config]
#n_lstm_layer=1
#vocab_size=10000
#num_steps=35
#embedding_size=642
#
#num_units=642
#num_units_hyper=32
#embedding_dim=16
